var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};
$jscomp.polyfill=function(a,b,d,c){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,c):$jscomp.polyfillUnisolated(a,b,d,c))};$jscomp.polyfillUnisolated=function(a,b,d,c){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];if(!(e in d))return;d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,c){var e=a.split(".");a=1===e.length;c=e[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var h=e[f];if(!(h in c))return;c=c[h]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?c[e]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==d&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(c,e,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,f){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,c=function(e){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+d++,e)};return c},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var c=$jscomp.global[b[d]];"function"===typeof c&&"function"!=typeof c.prototype[a]&&$jscomp.defineProperty(c.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var d=0,c=!1,e={next:function(){if(!c&&d<a.length){var f=d++;return{value:b(f,a[f]),done:!1}}c=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
var nMap={map:null,defaultSize:null,oInfoWnd:null,viewType:"",defaultLevel:10,eventFlg:!1,infoWindowData:[],labelData:[],targetViewData:[],isPop:!1,defaultLatitude:37.5675451,defaultLongitude:126.9773356,windowHeight:0,markerImages:["/images/staOn_s0p.png","/images/staOn_s25p.png","/images/staOn_s50p.png","/images/staOn_s75p.png","/images/staOn_s100p.png"],markerErrImages:["/images/staErr_s0p.png","/images/staErr_s25p.png","/images/staErr_s50p.png","/images/staErr_s75p.png","/images/staErr_s100p.png"],
markerSmallImages:["/images/staOn_ss0p.png","/images/staOn_ss25p.png","/images/staOn_ss50p.png","/images/staOn_ss75p.png","/images/staOn_ss100p.png"],markerSmallErrImages:["/images/staErr_ss0p.png","/images/staErr_ss25p.png","/images/staErr_ss50p.png","/images/staErr_ss75p.png","/images/staErr_ss100p.png"],makerStopImages:["/images/staStop_s0p.png","/images/staStop_s25p.png","/images/staStop_s50p.png","/images/staStop_s75p.png","/images/staStop_s100p.png"],makerSmallStopImages:["/images/staStop_ss0p.png",
"/images/staStop_ss25p.png","/images/staStop_ss50p.png","/images/staStop_ss75p.png","/images/staStop_ss100p.png"],initMap:function(){nMap.map=null;$("#mapDiv").empty();nMap.setMap();nMap.detectCoveredMarker=!0},setMap:function(){var a=nMap.getCalcMapSize();nMap.setOption(a.w,a.h);nMap.windowHeight=a.h;a=new nhn.api.map.LatLng(nMap.defaultLatitude,nMap.defaultLongitude);nhn.api.map.setDefaultPoint("LatLng");nMap.map=new nhn.api.map.Map("mapDiv",{point:a,zoom:nMap.defaultLevel,mapMode:0,enableWheelZoom:!1,
enableDragPan:!0,enableDblClickZoom:!1,activateBicycleMap:!0,activateTrafficMap:!1,activateRealtyMap:!0,minMaxLevel:[1,14],size:nMap.defaultSize,detectCoveredMarker:!0});nMap.oInfoWnd=new nhn.api.map.InfoWindow;nMap.oInfoWnd.setVisible(!1);nMap.map.addOverlay(nMap.oInfoWnd);a=new nhn.api.map.ZoomControl;a.setPosition({left:5,bottom:5});a.setCenterMarkOptions(!0);nMap.map.addControl(a);nMap.map.attach("resize",nMap.resizableMapView);nMap.map.attach("click",nMap.clickZoonBtn)},clickZoonBtn:function(a){},
setMapCenterPosi:function(a,b){nMap.map.setCenter(new nhn.api.map.LatLng(a,b))},resizableMapView:function(a){},setOption:function(a,b){nMap.defaultSize={width:a,height:b}},makeStationMapInfo:function(){var a=nMap;if("object"===typeof a.targetViewData){for(var b=a.targetViewData.length,d={},c=0;c<b;c+=1){var e={imgSrc:a.getSharedImgSrc(a.targetViewData[c].shared,a.targetViewData[c].deviceBroken,a.targetViewData[c].stationUseYn),imgWidth:38,imgHeight:48,latitude:a.targetViewData[c].latitude,longitude:a.targetViewData[c].longitude,
title:a.targetViewData[c].stationName,smallImg:""};e=nMap.makeMarker(e);"list"===nMap.viewType?(d.lat=nMap.defaultLatitude,d.long=nMap.defaultLongitude):"search"===nMap.viewType&&"Y"===a.targetViewData[c].mainStationYn&&(d.lat=a.targetViewData[c].latitude,d.long=a.targetViewData[c].longitude);a.infoWindowData.push({sId:a.targetViewData[c].stationName,info:[{stationName:a.targetViewData[c].stationName,stationId:a.targetViewData[c].stationId,rackInfo:a.targetViewData[c].rackInfo,bikeInfo:a.targetViewData[c].bikeInfo,
longTerm:a.targetViewData[c].longTerm,shared:a.targetViewData[c].shared,stationImg:a.targetViewData[c].stationImgFileName}]});a.map.addOverlay(e)}"search"!==nMap.viewType||""==$("#stationGrpSeq").val()&&""==$("#paramSearchWord").val()||(c=d.lat,e=d.long,0===Object.keys(d).length&&(0<b&&--b,c=a.targetViewData[b].latitude,e=a.targetViewData[b].longitude),nMap.setMapCenterPosi(c,e));a.map.attach("click",a.showInfoWindow)}},makeMarker:function(a){var b="string"===typeof a.imgSrc?new nhn.api.map.Icon(a.imgSrc,
{width:a.imgWidth,height:a.imgHeight}):a.imgSrc;return new nhn.api.map.Marker(b,{point:new nhn.api.map.LatLng(a.latitude,a.longitude),zIndex:100,title:a.title,smallSrc:a.smallImg})},showInfoWindow:function(a){var b=nMap;if(void 0!==a){var d=a.target;if(d instanceof nhn.api.map.Marker){if(a.clickCoveredMarker)return!1;var c=d.getTitle();a=null;for(var e=0;e<b.infoWindowData.length;e+=1)if(b.infoWindowData[e].sId===c){a=b.infoWindowData[e].info;break}null!==a&&(nMap.oInfoWnd.setPoint(d.getPoint()),
b='<DIV  id="infoBox" style="border:2px solid #555; background:#fff; font-family:dotum; width:230px; text-align:left;" >       <p style="border-bottom:1px solid #c9c9c9; font-size:14px;color:#333; position:relative">           <span style="margin:10px 0 10px 10px; font-weight:bold; display:block;">'+(a[0].stationName+"</span>"),b=b+'           <a href="#" style="position:absolute; top:-3px; right:10px" class="mpclose"><img src="/images/stationClose.gif" alt="\ub300\uc5ec\uc18c \uc815\ubcf4\ub2eb\uae30" /></a>       </p>       <p style="display:inline-block; margin:5px; vertical-align:top;"><img src="'+
((""===a[0].stationImg?"/images/mapNoimg.gif":"data:image/gif;base64,"+a[0].stationImg)+'" style="width:50px; height:50px" alt="" /></p>       <ul style="display:inline-block; vertical-align:middle; font-size:14px;margin:5px;">'),b+='           <li>\uac70\uce58\ub300  : <span style="color:#000099;">'+a[0].rackInfo+"</span></li>",b+='           <li>\uc790\uc804\uac70  : <span style="color:#000099;">'+a[0].bikeInfo+"</span></li>",b+='           <li>\uac70\uce58\uc728(%)  : <span style="color:#000099;">'+
a[0].shared+"%</span></li>",nMap.oInfoWnd.setContent(b+'       </ul>       <p style="text-align:center; margin-bottom:-16px;"><img src="/images/stationPos.png" style="display:block; margin:0 auto;width:21px;height:16px;" alt="" /></p>   </DIV>'),nMap.oInfoWnd.setPosition({right:-115,top:45}),nMap.oInfoWnd.setVisible(!0),nMap.oInfoWnd.autoPosition(),$("#infoBox a").on("click",function(f){f.preventDefault();$("#infoBox").css("display","none")}))}}},getSharedImgSrc:function(a,b,d){var c=nMap,e=23,f=
29,h=c.map.getLevel(),g=parseInt(a);a=0;25>=g?a=1:50>=g?a=2:75>=g?a=3:75<g&&(a=4);0===g&&(a=0);7>h?(e=17,f=21,b=b?c.markerSmallErrImages[a]:c.markerSmallImages[a],"N"===d&&(b=c.makerSmallStopImages[a])):(b=b?c.markerErrImages[a]:c.markerImages[a],"N"===d&&(b=c.makerStopImages[a]));return new nhn.api.map.Icon(b,{width:e,height:f})},getCalcMapSize:function(){var a=0;isNaN(parseInt($("#content").css("padding-left")))||(a=parseInt($("#content").css("padding-left")));$(".rightBox")&&(a=$(".rightBox").innerWidth()+
20);a=$("#content").innerWidth()-a;"block"===$(".shBox_m").css("display")&&(a=$(".downtitle").innerWidth());var b=screen.height/2;null!==nMap.defaultSize&&(b=nMap.defaultSize.height);var d=nMap.defaultLevel;!nMap.isPop&&1E3<screen.height&&(b=500);2E3<a&&(a=735);400>a&&(d=6);return{l:d,w:a,h:b}}};window.onresize=function(){nMap.resize()};nMap.resize=function(a){a=nMap.getCalcMapSize();if(nMap.windowHeight!==a.h)return!1;var b=new nhn.api.map.Size(a.w,nMap.windowHeight);nMap.map.setSize(b);nMap.map.setLevel(a.l)};
