var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};
$jscomp.polyfill=function(a,b,d,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,e):$jscomp.polyfillUnisolated(a,b,d,e))};$jscomp.polyfillUnisolated=function(a,b,d,e){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];if(!(c in d))return;d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,e){var c=a.split(".");a=1===c.length;e=c[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<c.length-1;f++){var g=c[f];if(!(g in e))return;e=e[g]}c=c[c.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?e[c]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:b}):b!==d&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=
$jscomp.propertyToPolyfillSymbol[c],$jscomp.defineProperty(e,c,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(c,f){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,e=function(c){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(c||"")+"_"+d++,c)};return e},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var e=$jscomp.global[b[d]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&$jscomp.defineProperty(e.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var d=0,e=!1,c={next:function(){if(!e&&d<a.length){var f=d++;return{value:b(f,a[f]),done:!1}}e=!0;return{done:!0,value:void 0}}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
var nMap={map:null,defaultSize:null,oInfoWnd:null,viewType:"",defaultLevel:10,eventFlg:!1,infoWindowData:[],labelData:[],targetViewData:[],isPop:!1,defaultLatitude:37.5675451,defaultLongitude:126.9773356,windowHeight:0,markerImages:"/images/staOn_s0p.png /images/staOn_s25p.png /images/staOn_s50p.png /images/staOn_s75p.png /images/staOn_s100p.png /images/staStop_ss150p.png".split(" "),markerErrImages:"/images/staErr_s0p.png /images/staErr_s25p.png /images/staErr_s50p.png /images/staErr_s75p.png /images/staErr_s100p.png /images/staErr_s100p.png".split(" "),
markerSmallImages:"/images/staOn_ss0p.png /images/staOn_ss25p.png /images/staOn_ss50p.png /images/staOn_ss75p.png /images/staOn_ss100p.png /images/staStop_ss150p.png".split(" "),markerSmallErrImages:"/images/staErr_ss0p.png /images/staErr_ss25p.png /images/staErr_ss50p.png /images/staErr_ss75p.png /images/staErr_ss100p.png /images/staErr_s100p.png".split(" "),makerStopImages:"/images/staStop_s0p.png /images/staStop_s25p.png /images/staStop_s50p.png /images/staStop_s75p.png /images/staStop_s100p.png /images/staStop_ss150p.png".split(" "),
makerSmallStopImages:"/images/staStop_ss0p.png /images/staStop_ss25p.png /images/staStop_ss50p.png /images/staStop_ss75p.png /images/staStop_ss100p.png /images/staStop_ss150p.png".split(" "),initMap:function(){nMap.map=null;$("#mapDiv").empty();nMap.setMap();nMap.detectCoveredMarker=!0},setMap:function(){var a=nMap.getCalcMapSize();nMap.setOption(a.w,a.h);nMap.windowHeight=a.h;new naver.maps.LatLng(nMap.defaultLatitude,nMap.defaultLongitude);nMap.map=new naver.maps.Map("mapDiv",{size:new naver.maps.Size(a.w,
a.h),center:new naver.maps.LatLng(37.5675451,126.9773356),useStyleMap:!0,zoom:15,minZoom:8,zoomControl:!0,zoomControlOptions:{position:naver.maps.Position.RIGHT_BOTTOM}});nMap.map.setOptions("mapTypeControl",!0)},clickZoonBtn:function(a){},setMapCenterPosi:function(a,b){nMap.map.setCenter(new naver.maps.LatLng(a,b))},resizableMapView:function(a){},setOption:function(a,b){nMap.defaultSize={width:a,height:b}},makeStationMapInfo:function(){console.time("f1");var a=nMap,b=[];if("object"===typeof a.targetViewData){for(var d=
a.targetViewData.length,e={},c=0;c<d;c+=1)if(0>=parseInt(a.targetViewData[c].latitude))console.log(a.targetViewData[c].latitude);else{var f={imgSrc:a.getSharedImgSrc(a.targetViewData[c].shared,a.targetViewData[c].deviceBroken,a.targetViewData[c].stationUseYn),imgWidth:38,imgHeight:48,latitude:a.targetViewData[c].latitude,longitude:a.targetViewData[c].longitude,title:a.targetViewData[c].stationName,smallImg:""};f=nMap.makeMarker(f);"list"===nMap.viewType?(e.lat=nMap.defaultLatitude,e.long=nMap.defaultLongitude):
"search"===nMap.viewType&&"Y"===a.targetViewData[c].mainStationYn&&(e.lat=a.targetViewData[c].latitude,e.long=a.targetViewData[c].longitude);f.setMap(a.map);b.push(f);naver.maps.Event.addListener(b[c],"click",getClickHandler(c))}"search"!=nMap.viewType||""==$("#stationGrpSeq").val()&&""==$("#paramSearchWord").val()||(b=e.lat,c=e.long,0===Object.keys(e).length&&(0<d&&--d,b=a.targetViewData[d].latitude,c=a.targetViewData[d].longitude),0<b&&nMap.setMapCenterPosi(b,c));d=a.map.getCenter();a.map.setCenter(d);
console.timeEnd("f1")}}};
function getClickHandler(a){return function(b){b=null;b=nMap.targetViewData[a];var d='<DIV  id="infoBox" style="border:2px solid #555; background:#fff; font-family:dotum; width:230px; text-align:left;" >       <p style="border-bottom:1px solid #c9c9c9; font-size:14px;color:#333; position:relative">           <span style="margin:10px 0 10px 10px; font-weight:bold; display:block;">'+(b.stationName+"</span>");d=d+'           <a href="#" style="position:absolute; top:-3px; right:10px" class="mpclose"><img src="/images/stationClose.gif" alt="\ub300\uc5ec\uc18c \uc815\ubcf4\ub2eb\uae30" /></a>       </p>       <p style="display:inline-block; margin:5px; vertical-align:top;"><img src="/images/mapNoimg.gif" style="width:50px; height:50px" alt="" /></p>       <ul style="display:inline-block; vertical-align:middle; font-size:14px;margin:5px;">           <li>\uac70\uce58\ub300  : <span style="color:#000099;">'+(b.rackInfo+
"</span></li>");d+='           <li>\uc790\uc804\uac70  : <span style="color:#000099;">'+b.bikeInfo+"</span></li>";d+='           <li>\uac70\uce58\uc728(%)  : <span style="color:#000099;">'+b.shared+"%</span></li>";var e=new naver.maps.InfoWindow({content:d+'       </ul>       <p style="text-align:center; margin-bottom:-16px;"><img src="/images/stationPos.png" style="display:block; margin:0 auto;width:21px;height:16px;" alt="" /></p>   </DIV>'}),c=new naver.maps.LatLng(b.latitude,b.longitude);e.open(nMap.map,
c);$("#infoBox a").on("click",function(f){f.preventDefault();e.close(nMap.map,c)})}}nMap.makeMarker=function(a){var b=("string"===typeof a.imgSrc?{icon:{url:a.imgSrc,size:new naver.maps.Size(a.imgWidth,a.imgHeight)}}:a.imgSrc).icon.url;a={position:new naver.maps.LatLng(a.latitude,a.longitude),map:nMap.map,icon:{url:b,title:a.title}};return new naver.maps.Marker(a)};
nMap.showInfoWindow=function(a){var b=nMap;if(void 0!==a){var d=a.target;if(d instanceof naver.maps.Marker){if(a.clickCoveredMarker)return!1;var e=d.getTitle();a=null;for(var c=0;c<b.infoWindowData.length;c+=1)if(b.infoWindowData[c].sId===e){a=b.infoWindowData[c].info;break}null!==a&&(nMap.oInfoWnd.setPoint(d.getPoint()),b='<DIV  id="infoBox" style="border:2px solid #555; background:#fff; font-family:dotum; width:230px; text-align:left;" >       <p style="border-bottom:1px solid #c9c9c9; font-size:14px;color:#333; position:relative">           <span style="margin:10px 0 10px 10px; font-weight:bold; display:block;">'+
(a[0].stationName+"</span>"),b=b+'           <a href="#" style="position:absolute; top:-3px; right:10px" class="mpclose"><img src="/images/stationClose.gif" alt="\ub300\uc5ec\uc18c \uc815\ubcf4\ub2eb\uae30" /></a>       </p>       <p style="display:inline-block; margin:5px; vertical-align:top;"><img src="'+((""===a[0].stationImg?"/images/mapNoimg.gif":"data:image/gif;base64,"+a[0].stationImg)+'" style="width:50px; height:50px" alt="" /></p>       <ul style="display:inline-block; vertical-align:middle; font-size:14px;margin:5px;">'),
b+='           <li>\uac70\uce58\ub300  : <span style="color:#000099;">'+a[0].rackInfo+"</span></li>",b+='           <li>\uc790\uc804\uac70  : <span style="color:#000099;">'+a[0].bikeInfo+"</span></li>",b+='           <li>\uac70\uce58\uc728(%)  : <span style="color:#000099;">'+a[0].shared+"%</span></li>",nMap.oInfoWnd.setContent(b+'       </ul>       <p style="text-align:center; margin-bottom:-16px;"><img src="/images/stationPos.png" style="display:block; margin:0 auto;width:21px;height:16px;" alt="" /></p>   </DIV>'),
nMap.oInfoWnd.setPosition({right:-115,top:45}),nMap.oInfoWnd.setVisible(!0),nMap.oInfoWnd.autoPosition(),$("#infoBox a").on("click",function(f){f.preventDefault();$("#infoBox").css("display","none")}))}}};nMap.getSharedImgSrc=function(a,b,d){var e=nMap,c=parseInt(a);a=0;25>=c?a=1:50>=c?a=2:75>=c?a=3:130>=c?a=4:130<c&&(a=5);0===c&&(a=0);b=b?e.markerSmallErrImages[a]:e.markerSmallImages[a];"N"===d&&(b=e.makerSmallStopImages[a]);return{icon:{url:b,size:new naver.maps.Size(23,29)}}};
nMap.getCalcMapSize=function(){var a=0;isNaN(parseInt($("#content").css("padding-left")))||(a=parseInt($("#content").css("padding-left")));$(".rightBox")&&(a=$(".rightBox").innerWidth()+20);a=$("#content").innerWidth()-a;"block"===$(".shBox_m").css("display")&&(a=$(".downtitle").innerWidth());var b=screen.height/2;null!==nMap.defaultSize&&(b=nMap.defaultSize.height);var d=nMap.defaultLevel;!nMap.isPop&&1E3<screen.height&&(b=500);2E3<a&&(a=735);400>a&&(d=6);return{l:d,w:a,h:b}};window.onresize=function(){nMap.resize()};
nMap.resize=function(a){a=nMap.getCalcMapSize();if(nMap.windowHeight!==a.h)return!1;a=new naver.maps.Size(a.w,nMap.windowHeight);nMap.map.setSize(a)};
