var nMap={map:null,mapZoom:null,eventFlg:!1,infoWindowData:[],defaultSize:null,targetViewData:[],defaultLatitude:37.5675451,defaultLongitude:126.9773356,stationImgFilePath:"",defaultLevel:9,popType:"",infoWindowType:"",viewType:"",windowHeight:0,oInfoWnd:null,locationMarker:null},markers=[],oldMarkersLen=0;nMap.markerImages=["/images/inc/icon_b0.png","/images/inc/icon_b2.png","/images/inc/icon_b3.png","/images/inc/icon_b3.png","/images/inc/icon_b3_b.png"];
nMap.markerSmallImages=["/images/inc/icon_s0.png","/images/inc/icon_s2.png","/images/inc/icon_s3.png","/images/inc/icon_s3.png","/images/inc/icon_s3.png"];nMap.markerErrImages=["/images/inc/icon_b1.png","/images/inc/icon_b1.png","/images/inc/icon_b1.png","/images/inc/icon_b1.png","/images/inc/icon_b1.png"];nMap.markerSmallErrImages=["/images/inc/icon_s1.png","/images/inc/icon_s1.png","/images/inc/icon_s1.png","/images/inc/icon_s1.png","/images/inc/icon_s1.png"];
nMap.markerStopImages=["/images/inc/icon_b0.png","/images/inc/icon_b0.png","/images/inc/icon_b0.png","/images/inc/icon_b0.png","/images/inc/icon_b0.png"];nMap.markerSmallStopImages=["/images/inc/icon_s0.png","/images/inc/icon_s0.png","/images/inc/icon_s0.png","/images/inc/icon_s0.png","/images/inc/icon_s0.png"];
nMap.setMap=function(){if(null!==nMap.map)return!1;new naver.maps.LatLng(nMap.defaultLatitude,nMap.defaultLongitude);nMap.map=new naver.maps.Map("mapDiv",{center:new naver.maps.LatLng(37.5675451,126.9773356),zoom:10,minZoom:5,zoomControl:!1,zoomControlOptions:{position:naver.maps.Position.BOTTOM_RIGHT}})};nMap.initMap=function(){$("#mapDiv").empty();nMap.map=null;nMap.setMap();nMap.detectCoveredMarker=!0};nMap.resizableMapView=function(a){console.log("resizableMapView--\x3e"+a.size.height+","+a.size.width)};
nMap.setOption=function(a,b){nMap.defaultSize={width:a,height:b}};
nMap.makeStationMapInfo=function(a){var b=nMap;if("object"===typeof b.targetViewData){b.infoWindowType=""===b.infoWindowType?"station":b.infoWindowType;var d=b.targetViewData.length;if(0<d){for(var c=oldMarkersLen;c<oldMarkersLen+a;c+=1){var e=b.getSharedImgSrc(b.targetViewData[c].shared,b.targetViewData[c].deviceBroken,b.targetViewData[c].stationUseYn,b.targetViewData[c].teamNm),f=e.icon.content;e=e.icon.size;f={position:new naver.maps.LatLng(b.targetViewData[c].latitude,b.targetViewData[c].longitude),
map:nMap.map,icon:{content:f,size:e,title:b.targetViewData[c].stationName}};f=new naver.maps.Marker(f);markers.push(f);naver.maps.Event.addListener(markers[c],"click",getClickHandler(c))}oldMarkersLen+=a;"search"===nMap.viewType&&(a=d-1,nMap.setMapCenterPosi(b.targetViewData[a].latitude,b.targetViewData[a].longitude))}else a=nMap.getHitImg(b.map.getSize().height),nMap.makeMarker({imgSrc:a.src,imgWidth:a.w,imgHeight:a.h,latitude:b.defaultLatitude,longitude:b.defaultLongitude,title:"\ub300\uc5ec\uc18c",
smallImg:"/images/inc/staMap_shit.png"})}};
nMap.makeStationMapInfoClean=function(a,b){var d=nMap;oldMarkersLen=b;if("object"===typeof d.targetViewData)if(d.infoWindowType=""===d.infoWindowType?"station":d.infoWindowType,b=d.targetViewData.length,0<b){for(var c=oldMarkersLen;c<oldMarkersLen+a;c+=1){d.getSharedImgSrc(d.targetViewData[c].shared,d.targetViewData[c].deviceBroken,d.targetViewData[c].stationUseYn);var e={position:new naver.maps.LatLng(d.targetViewData[c].latitude,d.targetViewData[c].longitude),map:nMap.map,icon:{url:sURL,content:'<div style="position:relative; background:url(https://www.bikeseoul.com/images/inc/icon_b3.png) no-repeat; cursor: pointer; width: 20px; height: 23px;"><div style="text-align:center; font-size:11px; color:#fff; padding-top:2px">23</div></div>',
size:new naver.maps.Size(22,35),title:d.targetViewData[c].stationName}};e=new naver.maps.Marker(e);markers.push(e);naver.maps.Event.addListener(markers[c],"click",getClickHandler(c))}oldMarkersLen+=a;"search"===nMap.viewType&&(a=b-1,nMap.setMapCenterPosi(d.targetViewData[a].latitude,d.targetViewData[a].longitude))}else a=nMap.getHitImg(d.map.getSize().height),nMap.makeMarker({imgSrc:a.src,imgWidth:a.w,imgHeight:a.h,latitude:d.defaultLatitude,longitude:d.defaultLongitude,title:"\ub300\uc5ec\uc18c",
smallImg:"/images/inc/staMap_shit.png"})};nMap.changeMarker=function(){};nMap.setMapCenterPosi=function(a,b){nMap.map.setCenter(new naver.maps.LatLng(a,b))};
function getClickHandler(a){return function(b){$("#guide_box").css("display","none");var d=null;d=nMap.targetViewData[a];b=new Date;b.getFullYear();b.getMonth();b.getDate();b.getHours();b.getMinutes();b.getSeconds();b='<DIV  id="infoBox" style="border:2px solid #555; background:#fff; font-family:dotum; width:230px; text-align:left;" >       <p style="border-bottom:1px solid #c9c9c9; font-size:14px;color:#333; position:relative">           <span style="margin:10px 0 10px 10px; font-weight:bold; display:block;">'+(d.stationName+
"</span>");b=b+'           <a href="#" style="position:absolute; top:-3px; right:10px" class="closeBtn"><img src="/images/stationClose.gif" alt="\ub300\uc5ec\uc18c \uc815\ubcf4\ub2eb\uae30" /></a>       </p>       <ul style="display:inline-block; vertical-align:middle; font-size:14px;margin:5px;">           <li>\uac70\uce58\ub300  : <span style="color:#000099;">'+(d.rackInfo+"</span></li>");b+='           <li>\uc790\uc804\uac70  : <span style="color:#000099;">'+d.bikeInfo+"</span></li>";var c=new naver.maps.InfoWindow({content:b+
'           <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" id="detailBtn" class="detailBtn">\uc0c1\uc138\uc815\ubcf4</a></li>       </ul>       <p style="text-align:center; margin-bottom:-16px;"><img src="/images/stationPos.png" style="display:block; margin:0 auto;width:21px;height:16px;" alt="" /></p>   </DIV>'}),e=new naver.maps.LatLng(d.latitude,d.longitude);
c.open(nMap.map,e);$("#infoBox a").on("click",function(f){f.preventDefault();c.close(nMap.map,e)});$("#favoriteBtn").on("click",function(f){f.preventDefault();goFavoriteStation(d)});$("#closeBtn").on("click",function(f){f.preventDefault();c.close(nMap.map,e)});$("#detailBtn").on("click",function(f){f.preventDefault();moveStationDetail2(d.stationId)})}}
nMap.makeMarker=function(a){var b=("string"===typeof a.imgSrc?{icon:{url:a.imgSrc,size:new naver.maps.Size(a.imgWidth,a.imgHeight)}}:a.imgSrc).icon.url;a={position:new naver.maps.LatLng(a.latitude,a.longitude),map:nMap.map,icon:{url:b,content:'<div style="position:relative; background:url(https://www.bikeseoul.com/images/inc/icon_b3.png) no-repeat; cursor: pointer; width: 20px; height: 23px;"><div style="text-align:center; font-size:11px; color:#fff; padding-top:2px"><br>23</div></div>',title:a.title}};
return new naver.maps.Marker(a)};nMap.showInfoWindow=function(a){};
nMap.getSharedImgSrc=function(a,b,d,c){var e=nMap,f=20,h=23,k=3,g=parseInt(a);100<g&&(f=35,h=40,k=12);null==c&&(c="");a=0;25>=g?a=1:50>=g?a=2:100>=g?a=3:100<g&&(a=4);0===g&&(a=0);b=b?e.markerErrImages[a]:e.markerImages[a];"N"===d&&(b=e.makerStopImages[a]);return{icon:{url:b,content:'<div style="position:relative; background:url('+b+") no-repeat; cursor: pointer; width: "+f+"px; height: "+h+'px;"><div style="text-align:center; font-size:11px; color:#fff; padding-top:'+k+'px">'+c+"</div></div>",size:new naver.maps.Size(f,
h)}}};
nMap.getBikeInfoImgSrc=function(a,b){var d=nMap,c="",e=9,f=10;a=nMap.getBikeInfoIdx(parseInt(a));8<=nMap.map.zoom&&(e=20,f=23,4==a&&(e=30,f=43));"return"===d.infoWindowType?8>nMap.map.zoom?"good"===b||"less"===b?c=nMap.markerSmallImages[4]:"over"===b&&(c=nMap.markerSmallStopImages[4]):"good"===b||"less"===b?c=nMap.markerImages[4]:"over"===b&&(c=nMap.markerStopImages[4]):c=10>nMap.map.zoom?b?d.markerSmallStopImages[a]:d.markerSmallImages[a]:b?d.markerStopImages[a]:d.markerImages[a];return{icon:{url:c,size:new naver.maps.Size(e,
f)}}};nMap.getBikeInfoIdx=function(a){var b=0;1>a?b=4:3>=a?b=1:6>=a?b=2:6<a&&(b=3);0===a&&(b=4);return b};
nMap.setStationNearMallMap=function(){var a=nMap;if("object"===typeof a.targetViewData){a.infoWindowType="mall";var b=a.targetViewData.length;a.infoWindowData=[];for(var d=nMap.getHitImg(nMap.map.getSize().height),c=0;c<b;c+=1){var e=nMap.makeMarker({imgSrc:d.src,imgWidth:d.w,imgHeight:d.h,latitude:a.targetViewData[c].latitude,longitude:a.targetViewData[c].longitude,title:a.targetViewData[c].shopName,smallImg:"/images/inc/staMap_shit.png"});a.infoWindowData.push({sId:a.targetViewData[c].shopName,
info:[{stationName:a.targetViewData[c].stationName,shopAdSeq:a.targetViewData[c].shopAdSeq,shopName:a.targetViewData[c].shopName,shopTelNo:a.targetViewData[c].shopTelNo,typeClsName:a.targetViewData[c].typeClsName}]});a.map.addOverlay(e)}a.map.attach("click",a.showInfoWindow);1===b?a.map.setCenter(new naver.maps.LatLng(a.targetViewData[0].latitude,a.targetViewData[0].longitude)):(b=a.map.getCenter(),a.map.setCenter(b))}};
nMap.getHitImg=function(a){var b="/images/inc/staMap_hit.png",d=38,c=48;600>a&&(b="/images/inc/staMap_shit.png",d=23,c=28);return{src:b,w:d,h:c}};
nMap.searchCoordinateToAddress=function(a){var b=naver.maps.TransCoord.fromLatLngToTM128(a);infoWindowAddr.close();naver.maps.Service.reverseGeocode({location:b,coordType:naver.maps.Service.CoordType.TM128},function(d,c){if(d===naver.maps.Service.Status.ERROR)return alert("Something Wrong!");d=c.result.items;c=0;for(var e=d.length,f;c<e;c++)f=d[c],centerGu=f.addrdetail.sigugun;searchGuNum(centerGu);nMap.map.setCenter(a);-1===sigugun.indexOf(centerGu+",")&&(station.getMapData({stationGrpSeq:centerGuNo},
"infoBox"),sigugun=sigugun+centerGu+",")})};nMap.setGPSLoc=function(a,b){var d=40,c=40;600>nMap.map.getSize().height&&(c=d=40);nMap.setMapCenterPosi(a,b);d={imgSrc:"/images/inc/icon_position.png",imgWidth:d,imgHeight:c,latitude:a,longitude:b,title:"\ud604\uc7ac\uc704\uce58",smallImg:"/images/inc/icon_position.png"};null===nMap.locationMarker?nMap.locationMarker=nMap.makeMarker(d):nMap.locationMarker.setPosition(new naver.maps.LatLng(a,b))};
nMap.getCalcMapSize=function(a){if("single"===nMap.popType){var b=$("#"+a).innerHeight()-60;a=$("#"+a).innerWidth();"mall"===nMap.infoWindowType&&(a=$(".popcntbox").height(),b/=2,700<b&&(b+=a),a=$(".popcntbox").innerWidth()-2*parseInt($(".popcntbox").css("padding")))}else{void 0!==$("#container").offset()&&$("#container").offset();$("#container").innerWidth();var d=screen.height-($("header#gnbhead").height()+$(".pwTM").innerHeight()+$("footer").height());b=0;0<$(".newmapsta").length&&(b=$(".newmapsta").offset().top-
($(".pwPC").height()+$(".pwheader").height()),500>=screen.height?b=30:700>=screen.height?b=50:800>=screen.height&&(b-=150),d<b&&(b=0));"return"===nMap.infoWindowType&&(b+=450);a=$("#container").innerWidth()-3;b=d-b;100>b&&(b=d);$("body").attr("id");"return"!==nMap.infoWindowType&&"app"!==nMap.infoWindowType&&1E3<screen.height&&(b=500)}return{w:a,h:b}};window.onresize=function(a){nMap.resize()};nMap.resize=function(){var a=nMap.getCalcMapSize($("body").attr("id"));new naver.maps.Size(a.w,nMap.windowHeight)};
nMap.drawPolyLine=function(){var a=[],b=new naver.maps.Polyline;if(0<this.targetViewData.length)for(var d=this.targetViewData.length,c=0;c<d;c+=1)a.push(new naver.maps.LatLng(this.targetViewData[c].moveLatitude,this.targetViewData[c].moveLongitude));b.setPoints(a);b.setStyle({strokeColor:"#FF0000",strokeWidth:10,strokeOpacity:1,strokeStyle:"solid"});nMap.map.addOverlay(b)};
